# Generated by Django 3.2.12 on 2022-03-28 07:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_register_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='firstname',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='lastname',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='image',
            field=models.FileField(upload_to=models.CharField(max_length=20)),
        ),
    ]
