# Generated by Django 3.2.12 on 2022-03-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_register_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='image',
            field=models.FileField(upload_to='<django.db.models.fields.CharField>+<django.db.models.fields.CharField>'),
        ),
    ]
