# Generated by Django 3.2.12 on 2022-03-29 07:10

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_register_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='image',
            field=models.FileField(upload_to=core.models.get_image_path),
        ),
    ]
