# Generated by Django 3.2.12 on 2022-03-29 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_register_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.register')),
            ],
        ),
    ]
