# Generated by Django 3.2.12 on 2022-03-29 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_imageupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='image',
        ),
    ]
