# Generated by Django 3.2.12 on 2022-04-02 10:09

import core.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_imageupload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=core.models.get_image_path),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ImageUpload',
        ),
    ]
